### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Elfayer** [Elfayer/vue-land-bot#1]
### Legend:
:heavy_check_mark: Completed
:construction: In progress / To be done
:bulb: Idea, not started
**TBD** To Be Determined

## Commands

:construction: **`!help <command>`**: Allow to see all available commands. If contains an argument `command`, show the command usage.

:bulb: **`!start-qa <user1> <user2> ...`**: Would provide writing right on `#q-and-a` channel, also write an opening message welcoming `users` as guests tagged in args. (Could also provide `users` `q&a guest` rights for coloring.

:bulb: **`!end-qa`**: Would turn off writing right on `#q-and-a` channel, also write a closing message.

:heavy_check_mark: **`!code`**: (From Reactiflux bot) Provide guidance on how to use code highlighting.

:bulb: **`!ask`**: (From Reactiflux bot) Provide guidance to how to ask questions.

:heavy_check_mark: **`!doc <topic>`**: Would provide the doc page of the specified `topic`.

:bulb: **`!guide <topic>`**: Would provide the guide page of the specified `topic`. (Guide from Gusto and Dobromir)

:bulb: **`!jobs-report`**: List all actions taken by jobs last week (TBD). Should contain `which job` `who` and `when`.

## Jobs

:construction: **`ban`**: List of rules to ban.

:bulb: **`warn`**: List of rules to ping Moderators in `#room-with-a-vue` (or PM, TBD).

:bulb: **`q-and-a-management`**: (From Reactiflux) Only active during Q&A. Make sure there is no more than 3 questions ongoing, otherwise warn message. (Have to determine the counting)

:bulb: **`report`**: Every weekend (Sunday?) show on `#room-with-a-vue` the `!jobs-report`.

**Comment by sustained** [comment]
I created dedicated issues for each thing here to facilitate easier discussion and thus am closing this:

- `!help` - Built-in to Commando framework.
- `!start-qa`, `!end-qa`, `!q-and-a-management` - #21 
- `!ask` - #18
- `!code` - #19 
- `!doc` - #13
- `!guide` - #22

NOTE: Still need to create the moderation-command-related issues.
