### ISSUE TITLE
Question etiquette / "how to ask" command

### ISSUE THREAD

**Issue by sustained** [Elfayer/vue-land-bot#18]
This is copied verbatim from Naito's message on Discord:

- Don't `@` after every question
- If you're just starting a question don't directly `@` someone unless they're literally the only person who can help
- Don't make your question super vague / broad, try  to narrow it down to one thing you're struggling with rather than "Can you help me integrate X with Y"
- Don't post in multiple channels super quickly, if you're not getting a response after a long period of time from a non #code-help channel, link the question in #code-help
- People aren't getting paid for this, and they may not know how to solve your exact situation so your answer may not be answered (Naito has been waiting months!)
- Don't DM people without their permission
- Wrap code in code blocks
- If possible create a codepen or a codesandbox with an example of your problem, if you're unable to and have a lot of code to show, use a gist or pastebin (try to make sure the syntax highlighting is right)
- Be patient

Also the question etiquette command should really take a second argument which is language so we can have this translated, possibly a numbered list so that we can highlight a certain number.

**Comment by lloydjatkinson** [comment]
Maybe we should have a link to https://stackoverflow.com/help/how-to-ask as well because that’s a pretty good list I’ve found

**Comment by sustained** [comment]
That's probably a good idea.

**Comment by sustained** [comment]
Closed by #49.
